export enum Role {
    SUPER_ADMIN = "SUPER_ADMIN",
    ORG_ADMIN = "ORG_ADMIN",
    WORKSPACE_ADMIN = "WORKSPACE_ADMIN",
    PROJECT_MANAGER = "PROJECT_MANAGER",
    TEAM_LEAD = "TEAM_LEAD",
    USER = "USER",
    GUEST = "GUEST"
}